# Generated by Django 3.1.4 on 2020-12-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedyCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='عرض الحاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصوره')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.needy')),
            ],
        ),
    ]
