# Generated by Django 3.1.4 on 2020-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needycase',
            name='image',
        ),
        migrations.AddField(
            model_name='needycase',
            name='case_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'دعم الكهرباء'), (2, 'دعم الغذاء'), (3, 'دعم التعليم'), (4, 'دعم الماء'), (5, 'دعم الملبس')], null=True, verbose_name='نوع الحاله'),
        ),
    ]
