# Generated by Django 3.0.7 on 2020-12-04 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ammount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.NeedyCase'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
