# Generated by Django 3.0.7 on 2020-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='paper',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
