# Generated by Django 3.1.2 on 2020-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_certificate_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebaKheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='الهويه')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name='المبلغ')),
            ],
        ),
    ]
