# Generated by Django 3.1.4 on 2020-12-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_tamkeensupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamkeensupply',
            name='tamkeen_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'تمكين منتهى بتدريب'), (2, 'تمكين منتهى بمقابل مادى'), (3, 'تمكين منتهى بفرصة عمل')], null=True),
        ),
    ]
