# Generated by Django 3.1.4 on 2020-12-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20201225_1538'),
        ('cases', '0011_auto_20201225_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.needy'),
        ),
    ]
