# Generated by Django 3.1.2 on 2020-12-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20201225_1538'),
        ('cases', '0012_auto_20201225_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needycase',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.needy'),
        ),
    ]
