# Generated by Django 3.1.2 on 2021-01-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0014_volunteerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم')),
                ('user_type', models.SmallIntegerField(choices=[(1, 'مشرف'), (2, 'فاعل خير'), (3, 'مستفيد')], null=True, verbose_name='نوع المستخدم')),
                ('message', models.TextField(blank=True, null=True, verbose_name='الرساله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
