# Generated by Django 3.0.7 on 2020-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an volunteer. ', verbose_name='volunteer '),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير المؤسسه'), (2, 'مشرف جمعيه رئيسيه'), (3, 'مشرف جمعيه تنمويه'), (4, 'مشرف متعاون'), (5, 'محتاج'), (6, 'متبرع'), (7, 'متطوع')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
