# Generated by Django 3.0.7 on 2020-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='depend_child',
            field=models.ManyToManyField(null=True, to='office.Dependency', verbose_name='الأطفال'),
        ),
    ]
