# Generated by Django 3.0.7 on 2020-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_needy_total_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='amount',
            field=models.IntegerField(max_length=255, null=True, verbose_name='قيمة الدعم'),
        ),
    ]
