# Generated by Django 3.1.4 on 2020-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20201225_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='tamkeen',
            new_name='cases',
        ),
        migrations.AddField(
            model_name='courses',
            name='depend_child',
            field=models.ManyToManyField(null=True, to='office.Dependency', verbose_name='الأطفال'),
        ),
    ]
